# Generated by Django 4.0.4 on 2022-05-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountmodel',
            name='account_id',
            field=models.CharField(default='0000', max_length=150),
        ),
    ]
